server:
  port: 8081

spring:
  application:
    name: motoclub-service

  datasource:
    url: jdbc:h2:mem:motoclubdb
    driverClassName: org.h2.Driver
    username: sa
    password:
    platform: h2

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

  liquibase:
    enabled: false


